package main

import (
	"io"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"testing"
	"time"

	"github.com/tijszwinkels/dataverse-hub/auth"
	"github.com/tijszwinkels/dataverse-hub/realm"
	"github.com/tijszwinkels/dataverse-hub/serving"
	"github.com/tijszwinkels/dataverse-hub/storage"
	"github.com/tijszwinkels/dataverse-hub/upstream"
)

// TestProxyProblemResponses drives proxy-generated (locally-validated) error
// classes and asserts an RFC 9457 problem body. Table-driven per error class.
func TestProxyProblemResponses(t *testing.T) {
	proxySrv, _, cleanup := testRootAndProxy(t)
	defer cleanup()

	priv, pubkey := testKeypair(t)
	priv2, _ := testKeypair(t)
	_, otherPubkey := testKeypair(t)

	// A real stored object, to reuse its body for a ref-mismatch PUT.
	id := "aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa"
	ref := pubkey + "." + id
	stored := buildSignedObject(t, priv, noteItem(pubkey, id, []string{"dataverse001"}))
	if resp := doPut(t, proxySrv, ref, stored); resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		t.Fatalf("setup PUT: expected 201, got %d: %s", resp.StatusCode, body)
	}

	cases := []struct {
		name       string
		method     string
		path       string
		putRef     string
		body       []byte
		wantStatus int
		wantCode   string
	}{
		{
			name:       "get malformed ref",
			method:     http.MethodGet,
			path:       "/wp-config.php",
			wantStatus: http.StatusNotFound,
			wantCode:   "NOT_FOUND",
		},
		{
			name:       "inbound malformed ref",
			method:     http.MethodGet,
			path:       "/.env/inbound",
			wantStatus: http.StatusNotFound,
			wantCode:   "NOT_FOUND",
		},
		{
			name:       "put invalid envelope",
			method:     http.MethodPut,
			putRef:     pubkey + ".bbbbbbbb-2222-4222-8222-bbbbbbbbbbbb",
			body:       []byte("{ not json"),
			wantStatus: http.StatusBadRequest,
			wantCode:   "INVALID_OBJECT",
		},
		{
			name:       "put unauthorized realm",
			method:     http.MethodPut,
			putRef:     pubkey + ".cccccccc-3333-4333-8333-cccccccccccc",
			body:       buildSignedObject(t, priv, noteItem(pubkey, "cccccccc-3333-4333-8333-cccccccccccc", []string{otherPubkey})),
			wantStatus: http.StatusForbidden,
			wantCode:   "REALM_FORBIDDEN",
		},
		{
			name:       "put ref mismatch",
			method:     http.MethodPut,
			putRef:     pubkey + ".dddddddd-4444-4444-8444-dddddddddddd",
			body:       stored,
			wantStatus: http.StatusBadRequest,
			wantCode:   "REF_MISMATCH",
		},
		{
			name:       "put bad signature",
			method:     http.MethodPut,
			putRef:     pubkey + ".eeeeeeee-5555-4555-8555-eeeeeeeeeeee",
			body:       buildSignedObject(t, priv2, noteItem(pubkey, "eeeeeeee-5555-4555-8555-eeeeeeeeeeee", []string{"dataverse001"})),
			wantStatus: http.StatusBadRequest,
			wantCode:   "INVALID_SIGNATURE",
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			var resp *http.Response
			switch c.method {
			case http.MethodGet:
				resp = doGet(t, proxySrv, c.path)
			case http.MethodPut:
				resp = doPut(t, proxySrv, c.putRef, c.body)
			}
			assertProblem(t, resp, c.wantStatus, c.wantCode)
		})
	}
}

// TestProxyForwardsUpstreamProblem verifies that an error generated by upstream
// (a 409 revision conflict) is relayed to the client as problem+json — the
// forwardResponse path preserves the upstream Content-Type.
func TestProxyForwardsUpstreamProblem(t *testing.T) {
	proxySrv, _, cleanup := testRootAndProxy(t)
	defer cleanup()

	priv, pubkey := testKeypair(t)
	id := "10000010-2222-4222-8222-222222222222"
	ref := pubkey + "." + id

	data5 := signedObjectWithRevision(t, priv, pubkey, id, []string{"dataverse001"}, "NOTE", 5)
	if resp := doPut(t, proxySrv, ref, data5); resp.StatusCode != http.StatusCreated {
		t.Fatalf("PUT rev5: got %d", resp.StatusCode)
	}
	// rev3 is forwarded to upstream (global object); upstream rejects with 409.
	data3 := signedObjectWithRevision(t, priv, pubkey, id, []string{"dataverse001"}, "NOTE", 3)
	resp := doPut(t, proxySrv, ref, data3)
	assertProblem(t, resp, http.StatusConflict, "REVISION_CONFLICT")
}

// TestProxyAuthRealmsUnauthorizedProblem covers /auth/realms in proxy mode.
func TestProxyAuthRealmsUnauthorizedProblem(t *testing.T) {
	proxySrv, _, cleanup := testRootAndProxy(t)
	defer cleanup()

	resp := doGet(t, proxySrv, "/auth/realms")
	assertProblem(t, resp, http.StatusUnauthorized, "UNAUTHORIZED")
}

// TestProxyRateLimitedProblem covers the 429 class in proxy mode. The proxy's
// own limiter rejects before any upstream call, so upstream is a dead address.
func TestProxyRateLimitedProblem(t *testing.T) {
	dir := t.TempDir()
	store, err := storage.NewStore(dir, true)
	if err != nil {
		t.Fatal(err)
	}
	shared := realm.NewSharedRealms()
	index := storage.NewIndex(shared)
	limiter := auth.NewRateLimiter(2, 1000)
	authStore := auth.NewAuthStore(168 * time.Hour)
	up := upstream.NewClient("http://127.0.0.1:1") // unreachable; never reached
	pending := upstream.NewSyncPending(filepath.Join(dir, "sync_pending"), up, store, index)
	proxy := serving.NewProxy(store, index, limiter, authStore, "", up, pending, shared)
	srv := httptest.NewServer(proxy.Router())
	defer func() {
		srv.Close()
		limiter.Stop()
		authStore.Stop()
	}()

	_, pubkey := testKeypair(t)
	path := "/" + pubkey + ".88888888-2222-4222-8222-222222222222"

	var got *http.Response
	for i := 0; i < 6; i++ {
		req, _ := http.NewRequest(http.MethodGet, srv.URL+path, nil)
		req.Header.Set("X-Forwarded-For", "203.0.113.9")
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatal(err)
		}
		if resp.StatusCode == http.StatusTooManyRequests {
			got = resp
			break
		}
		resp.Body.Close()
	}
	if got == nil {
		t.Fatal("never got 429 from proxy rate limiter")
	}
	assertProblem(t, got, http.StatusTooManyRequests, "RATE_LIMITED")
}
